openapi: 3.0.0
info:
  title: Loc8r API
  version: 1.0.0
  description: RESTful API for Locations and Points of Interest
  contact:
    name: Carlos Quesada Pérez
    email: cqp111@inlumine.ual.es

# servers:
#   - url: "http://localhost:3000/api"

paths:
  /usuarios:
    get:
      summary: Obtener lista de usuarios
      description: Recupera una lista de usuarios de la base de datos.
      operationId: getUsuarios
      tags:
        - Usuarios
      responses:
        '200':
          description: Lista de usuarios recuperada con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
        '500':
          description: Error interno del servidor
  /usuarios/{id}:
    get:
      summary: Obtener un usuario por ID
      description: Recupera los detalles de un usuario específico.
      operationId: getUsuarioPorId
      tags:
        - Usuarios
      parameters:
        - name: id
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '404':
          description: Usuario no encontrado

components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          description: ID del usuario
        nombre:
          type: string
          description: Nombre completo del usuario
        email:
          type: string
          description: Correo electrónico del usuario
        fecha_creacion:
          type: string
          format: date-time
          description: Fecha de creación de la cuenta
      required:
        - id
        - nombre
        - email
